COS301-SE-2022/Gym-King

.gitignore
back-end/index.js

Some changes with regards to checking working backend calls. (just sends website back to caller)
Added gitignore for node_modules.

🧱 Small change to back-end and add gitignore.

---

front-end/package.json
nx.json

This PR is used to test the CI-CD

change default project

---

front-end/src/App.tsx
front-end/src/components/dropdown/dropdown.tsx
front-end/src/pages/Home.tsx
front-end/src/pages/UploadActivityPage/UploadActivityPage.css
front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
front-end/src/theme/variables.css

Created the UploadActivity page and made a few CSS changes to the dropdown component.

Add UploadActivityPage

---

front-end/src/components/approvalButton/approvalButton.css
front-end/src/components/approvalButton/approvalButton.tsx
front-end/src/pages/Home.tsx
front-end/src/theme/variables.css

Added a new component that can be re-used in the pending approvals page.

Added new ApprovalButton component

---

front-end/src/components/approvalButton/approvalButton.css
front-end/src/components/approvalButton/approvalButton.tsx

Changed the button to a list item for display purposes.

Updated ApprovalButton

---

front-end/public/index.html
front-end/src/App.tsx
front-end/src/pages/AddGym/AddGym.css
front-end/src/pages/AddGym/AddGym.tsx

created the layout for the AddGymPage

✨  (UI) Add AddGymPage

---

front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.css
front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx

Adding the User Interface for the PendingApprovalsPage

Adding PendingApprovalsPage

---

front-end/src/components/AcceptRejectCard/AcceptRejectCard.css
front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
front-end/src/components/ActivityList/ActivityList.tsx
front-end/src/pages/Home.tsx

Created ActivityList and AcceptRejectCard components to add to the AcceptRejectPage.

Added components

---

front-end/src/App.tsx
front-end/src/pages/AcceptRejectPage/AcceptReject.css
front-end/src/pages/AcceptRejectPage/AcceptReject.tsx

Added new components to the page. 
Note that sample data has been used, the page will be connected to the API soon.

Updated AcceptRejectPage

---

front-end/src/components/approvalButton/approvalButton.tsx
front-end/src/pages/AcceptRejectPage/AcceptReject.tsx

Enabled data to be passed from PendingApprovalsPage to AcceptRejectPage.

Updated Navigation

---

front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx

Added the GET and POST requests to some of the pages. Not fully functional yet as there is no data in the tables.

Updated API calls

---

front-end/src/pages/UploadActivityPage/UploadActivityPage.test.tsx

Created a basic unit test that just checks if the page renders without errors.
It passed the test.

Created Unit Test for UploadActivityPage

---

front-end/src/components/SelectGym-Map/SelectGymMap.tsx
front-end/src/pages/AddGym/AddGym.tsx
front-end/src/pages/AddGymLocation/AddGymLocation.css
front-end/src/pages/AddGymLocation/AddGymLocation.tsx

removed the absolute icon, and added a pigeon-map overlay

🩹 fixed map-icon positioning with an overlay

---

front-end/src/components/SelectGym-Map/SelectGymMap.tsx
front-end/src/pages/AddGym/AddGym.tsx

we can now add a gym's details

✨ Add AddGym API Call

---

front-end/src/pages/AddGym/AddGym.tsx

added toast to notify users that api call was successful(green toast) or failed (red toast)
mmmmmtoast

💄 (UI): added toast 🍞 

---

back-end/gymkingheroku.ts

🧱 Changes to server APIs

---

front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx

added to toast to show user his/her upload was successful.
mmmToast

💄 (UI): Added toast to upload activity page 🍞🍞 

---

front-end/src/pages/AddGym/AddGym.tsx

The wrong variable was being posted to the database

🩹 Changed coordinate variables

---

front-end/src/App.tsx
front-end/src/pages/CreateBadgePage/CreateBadge.tsx
front-end/src/theme/variables.css

Just the UI components - still have to add the component functionality and connect to API.

Created CreateButtonPage

---

front-end/src/App.tsx
front-end/src/pages/CreateBadgePage/CreateBadge.tsx
front-end/src/pages/EditBadgePage/EditBadge.tsx
front-end/src/pages/UploadActivityPage/UploadActivityPage.css
front-end/src/theme/variables.css

Just the UI components - functionality still needs to be added.

Adding EditBadge page

---

front-end/src/pages/EditBadgePage/EditBadge.tsx

**Added a GET request to get the current info of the selected badge.** 
Still need to add default values for the dropdowns. 
Still need to add PUT request. 
Needs tests

Updated the EditBadge page

---

front-end/src/components/dropdown/dropdown.tsx
front-end/src/pages/CreateBadgePage/CreateBadge.tsx
front-end/src/validation/CreateBadgeValidation.tsx

Added form validation, API requests, and navigation. 
The only thing that needs to be looked at is the gym name/location dropdown.
Needs tests.

CreateBadge updated

---

back-end/gymkingheroku.test.ts

✅ Added Post API tests.

---

back-end/gymkingheroku.test.ts
back-end/gymkingheroku.ts

Adding more tests to server API.
Fixed an incorrect output of an API.

🧱 ✅ Added Post API tests and changed JSON return.

---

front-end/src/components/dropdown/dropdown.tsx
front-end/src/components/segmentButton/segmentButton.tsx
front-end/src/pages/EditBadgePage/EditBadge.tsx
front-end/src/pages/EditBadgePage/edit.tsx

Still need to implement the Delete functionality. 
Changed dropdowns to segment buttons because they work better and are easier to use.

Updated EditBadge Page

---

front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
front-end/src/components/ActivityList/ActivityList.test.tsx
front-end/src/components/activityInputs/ActivityInputs.test.tsx
front-end/src/components/approvalButton/approvalButton.test.tsx
front-end/src/components/dropdown/dropdown.test.tsx
front-end/src/components/filechooser/FileChooser.test.tsx
front-end/src/components/map/MapView.test.tsx

Just added comments (possible test cases) to some of the test files

Updated Test Files

---

front-end/src/components/radioGroup/radioGroup.tsx
front-end/src/components/segmentButton/segmentButton.tsx
front-end/src/pages/CreateBadgePage/CreateBadge.tsx
front-end/src/theme/variables.css
front-end/src/validation/CreateBadgeValidation.tsx

This page is basically done. 
It might need some styling fixes.
The only thing that is not implemented is the image functionality.

Updated CreateBadge page

---

front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.css
front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
front-end/src/pages/EditBadgePage/EditBadge.tsx
front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx

-created view badge page for gym owners to view all their gyms and badges belonging to  a specific gym.
-needs testing and minor some styling alterations

✨ (UI) : Create ViewBadge page for GymOwners

---

front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.css
front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
front-end/src/components/ViewBadgeCard/ViewBadgeCard.css
front-end/src/components/ViewBadgeCard/ViewBadgeCard.tsx
front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.test.tsx
front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx

added  a simple render test, more rigorous testing required

✨ (UI)view badges : Fix Grid Spacing and styling for narrower screens

---

front-end/src/components/segmentButton/segmentButton.tsx
front-end/src/pages/EditBadgePage/EditBadge.tsx

Edit and delete functionality is now working

Fixed EditBadge Page

---

back-end/users/users.test.ts
back-end/users/users.ts

- Adding API call use to calculate the leaderboard of gym.
- done by returning usernames and the

✅ 🧱 Adding API and Test for it.

---

front-end/src/components/LeaderBoardSwiper/LeaderBoardValues/LeaderboardValues.tsx
front-end/src/components/LeaderBoardSwiper/LeaderboardSwiper.tsx
front-end/src/pages/Leaderboard/Leaderboard.tsx

Implemented api, and leadboard logic

✨ (UI) Leaderboards - Implement Api

---

back-end/src/entities/badge.entity.ts
back-end/src/entities/badge_claim.entity.ts
back-end/src/entities/badge_owned.entity.ts

🍱 adding Entity

---

front-end/src/components/BurgerMenu/BurgerMenu.tsx
front-end/src/components/toolbar/Toolbar.tsx
front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx

made a burger menu for navigation and made it generalized so it can be used for the other user-types aswell. added menubutton to toolbar component

✨ Add Burger menu component

---

front-end/src/components/map/MapView.tsx

🔥 remove test button from user map 
✨ map now refreshes every second

Feature-Map

---

front-end/src/components/GymCard/GymCard.css
front-end/src/components/GymCard/GymCard.tsx
front-end/src/pages/ManageGyms/ManageGyms.tsx

created a page where manager can view all their gyms, and can add, delete or edit a gym.
layout is done.
need to implement api for it. needs tests

✨ Feature: create manage gyms

---

front-end/src/App.tsx
front-end/src/components/BurgerMenu/BurgerMenu.css
front-end/src/components/BurgerMenu/BurgerMenu.tsx
front-end/src/components/toolbar/Toolbar.tsx
front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
front-end/src/pages/ManageGyms/ManageGyms.tsx
front-end/src/pages/MyBadge/MyBadge.tsx
front-end/src/pages/UserMap/UserMap.tsx

minor fixes:
-made toolbar generalized
-made burgermenu direct routingDirection  forward
-added tool bar to usermap

added navigation

---

back-end/src/employees/employees.ts
back-end/src/repositories/badge.repository.ts
front-end/src/pages/EditBadgePage/EditBadge.tsx

- Changing Front end edit badge API call.
- Changing edit badge API call on back - end.
- Adding a edit badge in badge repository.

👽️Updating API calls for front end

---

front-end/src/pages/LoginPage/Login.tsx

Updated the API calls:
Login page should be able to login a user, employee and owner.
Register page registers a user.

Updated Login/Register

---

front-end/src/App.tsx
front-end/src/components/GymCard/GymCard.tsx
front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
front-end/src/pages/EditGymPage/EditGym.css
front-end/src/pages/EditGymPage/EditGym.tsx
front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
front-end/src/pages/GymOwnerPage/GymOwnerPage.tsx
front-end/src/pages/LoginPage/Login.tsx
front-end/src/pages/ManageGyms/ManageGyms.tsx
front-end/src/pages/UserMap/UserMap.tsx

add editgympage, and linked a few otherpages

add editGym page

---

back-end/src/owners/owners.ts
back-end/src/repositories/badge.repository.ts
front-end/src/pages/AddGym/AddGym.tsx
front-end/src/pages/EditGymPage/EditGym.tsx

- Changing rest of owners API calls to typeORM.
- Fixing a bug in badge repository.

🧱 Changing API calls and repository

---

front-end/src/components/GymCard/GymCard.css
front-end/src/components/GymCard/GymCard.tsx
front-end/src/components/SelectGym-Map/SelectGymMap.tsx
front-end/src/pages/AddGym/AddGym.tsx
front-end/src/pages/AddGymLocation/AddGymLocation.tsx
front-end/src/pages/EditBadgePage/EditBadge.tsx
front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
front-end/src/pages/ManageGyms/ManageGyms.tsx

redid layout for the addgym feature(to look more likemockup)
-add modal to search and select addresses
-allows gymowner to use his/her location
-add recenter functionality
-add lock button to lock position of gym on map
restructured code,now  uses sessionstorage to pass values across pages

change code for add gym

---

back-end/src/entities/user_otp.entity.ts
back-end/src/repositories/gym_user.repository.ts
back-end/src/repositories/user_otp.repository.ts
back-end/src/users/users.ts
back-end/src/utils/utils.ts

- Adding new user APIs with small security.
- Adding user OTP entity.
- Adding user OTP repository.

🧱New APIs for user OTP and repository and entity.

---

back-end/src/repositories/badge_claim.repository.ts
back-end/src/repositories/badge_owned.repository.ts
back-end/src/users/users.ts

- Adding working functionality to back end for user.
- Changing badge_claim and badge_owned to delete all instances of a user if user is deleted.

🧱Adding OTP functionality to users.

---

front-end/src/pages/EmployeeProfile/EmployeeProfile.css
front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
front-end/src/pages/LoginPage/Login.tsx
front-end/src/pages/OwnerProfile/OwnerProfile.tsx
front-end/src/pages/UserProfile/UserProfile.tsx
front-end/src/theme/variables.css
package.json
yarn.lock

Uses email address to login instead of username

Updated Login

---

back-end/src/entities/gym_employee.entity.ts
back-end/src/owners/owners.ts
back-end/src/repositories/badge.repository.ts
back-end/src/repositories/badge_claim.repository.ts
back-end/src/repositories/badge_owned.repository.ts
back-end/src/repositories/gym_owner.repository.ts
back-end/src/users/users.ts
front-end/src/pages/UserPendingBadges/PendingBadges.tsx
front-end/src/pages/UserProfile/UserProfile.tsx

- Adding get employees under an owner API call.
- Changing repositories to correct call findBy() instead of find()
- Changing employee entity to return their g_id.

🧱New API and changes to entity and repositories.

---

front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
front-end/src/components/BurgerMenu/BurgerMenu.tsx
front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
front-end/src/pages/AddEmployee/AddEmployee.tsx
front-end/src/pages/CreateBadgePage/CreateBadge.tsx
front-end/src/pages/LoginPage/Login.tsx
front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx

specifically when going back after performing a function such as accepting a claim

🩹 Fixed routing

---

.github/workflows/nxtest.yml
back-end/.gitignore
back-end/package.json
back-end/src/datasource.ts
back-end/src/employees/employees.test.ts
back-end/src/employees/employees.ts
back-end/src/entities/badge.entity.ts
back-end/src/index.ts
back-end/src/owners/owners.test.ts
back-end/src/owners/owners.ts
back-end/src/users/users.test.ts
back-end/src/utils/utils.test.ts
back-end/src/utils/utils.ts
back-end/tsconfig.json

- Changing entities to say what column type they are.
- Changing datasource to change depending on testing or production.
- Changing server for testing as well.
- Adding finished tests to users and employees.

✅🧱Changing entity, datasource, server with tests.

---

back-end/src/entities/gym.entity.ts
back-end/src/entities/gym_brand.entity.ts
back-end/src/entities/gym_employee.entity.ts
back-end/src/entities/gym_owner.entity.ts
back-end/src/entities/gym_user.entity.ts
back-end/src/repositories/friend.repository.ts
back-end/src/repositories/gym_user.repository.ts
back-end/src/users/users.test.ts
back-end/src/users/users.ts

- merging with most recent heroku server.

Update with current heroku server!

---

front-end/src/components/map/MapView.css

Bug was "unexpected unknown unit 'pxt'"

Fixed Bug by changing pxt to px
